############################ Default configuration #########################
baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Power Platform Tips & Tricks"

paginate = 20
enableEmoji = true

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[params]
  # DoIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 4
[[menu.main]]
    identifier = "glossary"
    pre = ""
    post = ""
    name = "Glossary"
    url = "/glossary/"
    title = ""
    weight = 5
[[menu.main]]
    identifier = "aboutme"
    pre = ""
    post = ""
    name = "About me"
    url = "/Aboutme/"
    title = ""
    weight = 6     
[[menu.main]]
    identifier = "speaking"
    pre = ""
    post = ""
    name = "Speaking"
    url = "/speakingengagements/"
    title = ""
    weight = 7
[[menu.main]]
    identifier = "videos"
    pre = ""
    post = ""
    name = "Videos"
    url = "/videos/"
    title = ""
    weight = 8
[[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 9
[[menu.main]]
    identifier = "recommended"
    pre = ""
    post = ""
    name = "Awesome people"
    url = "/recommended/"
    title = ""
    weight = 10           

[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  gravatarEmail = ""
  # URL of avatar shown in home page
  avatarURL = "image.jpg"
  social = true

[params.header.title]
      # URL of the LOGO
      logo = "/logo.png"
      # title name
      name = "Power Platform Tips & Tricks"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # {{< version 0.2.5 >}} whether to use typeit animation for title name
      typeit = true

[params.social]
    Twitter="@NathLeenders" 
    LinkedIn="nathalie-leenders-den-nijs-8853871b/"
    Github="Nathalie-Leenders"
    Email="info@nathalieleenders.com"

# Google analytics
[params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-G0R550W0TM"
      anonymizeIP = true

[page.comment.utterances]

  enable = true

  # owner/repo

  repo = "Nathalie-Leenders/BlogPosts"

  # issueTerm = "pathname"

  label = ""

  lightTheme = "github-light"

  darkTheme = "github-dark"

[page.comment]

  enable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enable = true
  # type of search engine ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # DoIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # DoIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # DoIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # DoIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""
  [params.search.fuse]
    # DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
