############################ Default configuration #########################
baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Power Platform Tips & Tricks"

# Change the default theme to be use when building the site with Hugo
theme = "DoIt"

[params]
  # DoIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
[[menu.main]]
    identifier = "glossary"
    pre = ""
    post = ""
    name = "Glossary"
    url = "/glossary/"
    title = ""
    weight = 4    
[[menu.main]]
    identifier = "speaking"
    pre = ""
    post = ""
    name = "Speaking at events"
    url = "/speakingengagements/"
    title = ""
    weight = 5
[[menu.main]]
    identifier = "videos"
    pre = ""
    post = ""
    name = "Videos"
    url = "/videos/"
    title = ""
    weight = 6
[[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 7          

[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  gravatarEmail = ""
  # URL of avatar shown in home page
  avatarURL = "image.jpg"
  social = true

[params.social]
    Twitter="@NathLeenders" 
    LinkedIn="nathalie-leenders-den-nijs-8853871b/"
    Github="Nathalie-Leenders"


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
